language: node_js

node_js:
  - "0.12"
  - "4"
  - "6.8"

before_script:
  - $(npm bin)/testem launchers

script:
  - npm test
  - npm run build
  - npm run ci-browser-test

branches:
  except:
    - gh-pages
